apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: skaffold-dev
build:
  artifacts:
    - image: akgupta47/go-pod
      context: src
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
